"""Adaugat cancel Factura in modelul Invoice

Revision ID: 51c1cb4024b3
Revises: 8b6a27bdae68
Create Date: 2025-07-21 10:28:06.810589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51c1cb4024b3'
down_revision: Union[str, Sequence[str], None] = '8b6a27bdae68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('is_cancelled', sa.Boolean(), nullable=False))
    op.add_column('invoices', sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    op.add_column('invoices', sa.Column('cancellation_reason', sa.String(length=500), nullable=True))
    op.add_column('invoices', sa.Column('cancelled_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoices', 'staff', ['cancelled_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'cancelled_by_id')
    op.drop_column('invoices', 'cancellation_reason')
    op.drop_column('invoices', 'cancelled_at')
    op.drop_column('invoices', 'is_cancelled')
    # ### end Alembic commands ###
