"""Modificari in tabelul ProductPrice

Revision ID: 8b6a27bdae68
Revises: 61684eea90dc
Create Date: 2025-07-18 10:45:06.710392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b6a27bdae68'
down_revision: Union[str, Sequence[str], None] = '61684eea90dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_prices', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_prices', 'is_active')
    # ### end Alembic commands ###
