"""Migrare legata de analitycs

Revision ID: d545a5c8c4d4
Revises: 51c1cb4024b3
Create Date: 2025-07-23 09:38:25.171121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd545a5c8c4d4'
down_revision: Union[str, Sequence[str], None] = '51c1cb4024b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_activities', sa.Column('referrer_source', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_activities', 'referrer_source')
    # ### end Alembic commands ###
